stages: [plato-build-test]

workflow:
  name: "Trigger branch: ${PARENT_BRANCH}"

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  FF_USE_FASTZIP: "true"
  ARTIFACT_COMPRESSION_LEVEL: fastest
  CACHE_COMPRESSION_LEVEL: fastest
  CLEAN_CACHE: "true"
  WIPE_CACHE: "none"

.pipeline-rules: &pipeline-rules
  - if: '$WIPE_CACHE != "none"'
    when: never
  - if: '$CI_PIPELINE_SOURCE == "web" && $REPO_PIPELINES == null'
  - if: '$CI_PIPELINE_SOURCE == "pipeline" && $REPO_PIPELINES == null'

.trigger-pipeline:
  rules:
    - *pipeline-rules
  variables:
    TRIGGER_BRANCH: ${PARENT_BRANCH}
    TRIGGER_SOURCE: ${PARENT_SOURCE}
  trigger:
    include: ci/pipeline.yml
    strategy: depend
  needs: []

.trigger-quality-check-pipeline:
  rules:
    - if: '$WIPE_CACHE != "none"'
      when: never
    - if: $CI_PIPELINE_SOURCE == "pipeline"
    - if: $CI_PIPELINE_SOURCE == "web"
  variables:
    TRIGGER_BRANCH: ${PARENT_BRANCH}
    TRIGGER_SOURCE: ${PARENT_SOURCE}
  trigger:
    include: ci/quality-check-pipeline.yml
    strategy: depend
  needs: []

trigger-quality-check:
  stage: plato-build-test
  extends: .trigger-quality-check-pipeline
  variables:
    SYSTEM: "cee-build033"
    EXECUTOR: ""

trigger-cpu:
  stage: plato-build-test
  extends: .trigger-pipeline
  variables:
    CONFIGURATION: "cpu"
    APPLICATION: "platoanalyze"
    SYSTEM: "cee-build034"
    EXECUTOR: ""
    CUSTOM_CI_BUILDS_DIR: "/scratch/plato-ci"

trigger-cpu-debug:
  stage: plato-build-test
  extends: .trigger-pipeline
  variables:
    CONFIGURATION: "cpu-debug"
    APPLICATION: "platoanalyze"
    SYSTEM: "cee-build060"
    EXECUTOR: ""
    RUN_COVERAGE_UNIT_TESTS: "true"
    SKIP_APP_REGRESSION_TESTS: "true"
    SKIP_PE_REGRESSION_TESTS: "true"

trigger-cpu-clang:
  stage: plato-build-test
  extends: .trigger-pipeline
  variables:
    CONFIGURATION: "cpu-clang-dev"
    APPLICATION: "platoanalyze"
    SYSTEM: "cee-build033"
    EXECUTOR: ""
    SKIP_APP_REGRESSION_TESTS: "true"
    SKIP_PE_REGRESSION_TESTS: "true"

trigger-optimism:
  stage: plato-build-test
  extends: .trigger-pipeline
  rules:
    - *pipeline-rules
    - if: '$CI_PIPELINE_SOURCE == "web" && $REPO_PIPELINES == "plato-python-app"'
    - if: '$CI_PIPELINE_SOURCE == "pipeline" && $REPO_PIPELINES == "plato-python-app"'
  variables:
    CONFIGURATION: "clang-optimism"
    APPLICATION: "plato-python-app"
    SYSTEM: "cee-build034"
    EXECUTOR: ""
    SKIP_PE_UNIT_TESTS: "true"
    SKIP_PE_REGRESSION_TESTS: "true"
    CUSTOM_SETUP_SCRIPT: "plato-python-app/utilities/setup-env.sh"
    CUSTOM_CI_BUILDS_DIR: "/scratch/plato-ci"

trigger-plato-cubit:
  stage: plato-build-test
  extends: .trigger-pipeline
  rules:
    - *pipeline-rules
    - if: '$CI_PIPELINE_SOURCE == "web" && $REPO_PIPELINES == "plato-cubit-geometry"'
    - if: '$CI_PIPELINE_SOURCE == "pipeline" && $REPO_PIPELINES == "plato-cubit-geometry"'
  variables:
    CONFIGURATION: "cpu"
    APPLICATION: "plato-cubit-geometry"
    SYSTEM: "cee-build033"
    EXECUTOR: ""
    SKIP_PE_REGRESSION_TESTS: "true"
    SKIP_APP_REGRESSION_TESTS: "true"
    CUSTOM_SETUP_SCRIPT: "plato-cubit-geometry/utilities/setup-env.sh"
    CUSTOM_CI_BUILDS_DIR: "/scratch/plato-ci"
    CUSTOM_CLONE_SCRIPT: "plato-cubit-geometry/utilities/create-cubit-spack-mirror.sh"

trigger-cpu-snopt:
  stage: plato-build-test
  extends: .trigger-pipeline
  variables:
    CONFIGURATION: "cpu-clang-snopt"
    APPLICATION: "platoanalyze"
    SYSTEM: "cee-build060"
    EXECUTOR: ""
    SKIP_APP_REGRESSION_TESTS: "true"
    SKIP_PE_REGRESSION_TESTS: "true"
    SKIP_APP_UNIT_TESTS: "true"

# Cache-wipe child pipelines:
# To use this, as a pipeline variable when launching, set WIPE_CACHE to "all" to wipe all caches, or 
# use the configuration whose cache you'd like to wipe, such as "cpu".

.trigger-cache-wipe:
  rules:
    - if: '$WIPE_CACHE != "none"'
  variables:
    TRIGGER_BRANCH: ${PARENT_BRANCH}
    TRIGGER_SOURCE: ${PARENT_SOURCE}
    TRIGGER_WIPE_CACHE: ${WIPE_CACHE}
  trigger:
    include: ci/cache-wipe-pipeline.yml
    strategy: depend
  needs: []

trigger-wipe-033:
  stage: plato-build-test
  extends: .trigger-cache-wipe
  variables:
    SYSTEM: "cee-build033"

trigger-wipe-034:
  stage: plato-build-test
  extends: .trigger-cache-wipe
  variables:
    SYSTEM: "cee-build034"

trigger-wipe-060:
  stage: plato-build-test
  extends: .trigger-cache-wipe
  variables:
    SYSTEM: "cee-build060"
