variables:
  GPU_ARCHITECTURE: 70
  SPACK_DEPENDENCY_KEY: spack_dependency_cache
  BUILD_CACHE_KEY: platoengine_build_cache
  REPORTS_ARTIFACTS_DIR: reports-dir
  LSAN_BLACKLIST_FILE: ci/detail/sanitizer_black_list.txt
  CPD_DIR: /pmd/pmd-bin-7.20.0/bin
  DEFAULT_SETUP_SCRIPT: utilities/setup-env.sh
  JOB_ID_AUD: https://cee-gitlab.sandia.gov
  CI_TOOLCHAIN_IMAGE: $CI_REGISTRY_IMAGE/ci-toolchain:latest
  CONTAINER_WORKSPACE_DIR: "/ci-workspace"
  RUN_IN_PODMAN: "podman run --env-host --rm -v $CI_PROJECT_DIR:$CONTAINER_WORKSPACE_DIR -w $CONTAINER_WORKSPACE_DIR $CI_TOOLCHAIN_IMAGE"

.base-job:
  hooks:
    pre_get_sources_script:
      - |
        if [[ $(which module) ]]; then
          module purge
          module load aue/git
          module load aue/git-lfs
          module load ccache
        fi
  id_tokens:
    CI_JOB_JWT:
      aud: ${JOB_ID_AUD}
