stages: [setup, build, test, teardown]

include:
  local: ci/*-templates.yml

merge-develop:
  stage: setup
  extends: .merge-with-develop
  tags:
    - ${CONFIGURATION}

setup-spack:
  stage: setup
  extends: .setup-local-spack-installation
  tags:
    - ${CONFIGURATION}
  needs: 
  - job: "merge-develop"
    optional: true

build-dependencies:
  stage: build
  extends: .build-and-cache-dependencies
  tags:
    - ${CONFIGURATION}
  needs: ["setup-spack"]

build-platoengine:
  stage: build
  extends: .build-and-cache-engine
  tags:
    - ${CONFIGURATION}
  needs: ["build-dependencies"]

build-platoanalyze:
  stage: build
  extends: .build-and-cache-analyze
  tags:
    - ${CONFIGURATION}
  needs: ["build-platoengine"]

generate-platoengine-unittests:
  stage: build
  extends: .generate-platoengine-unittests
  tags:
    - ${CONFIGURATION}
  needs: ["build-platoengine"]

unittest-platoengine:
  rules:
    - if: $CONFIGURATION == "dakota"
      when: never
    - when: on_success
  stage: test
  variables:
    CONFIGURATION: ${CONFIGURATION}
    CACHE_KEY: ${BUILD_CACHE_KEY}_${CI_PIPELINE_ID}
    TRIGGER_SOURCE: ${TRIGGER_SOURCE}
    TRIGGER_BRANCH: ${TRIGGER_BRANCH}
  trigger:
    include:
      - artifact: unittest-pipeline.yml
        job: generate-platoengine-unittests
    strategy: depend

test-platoengine:
  stage: test
  extends: .test-platoengine
  tags:
    - ${CONFIGURATION}
  needs: ["build-platoengine"]

unittest-platoanalyze:
  stage: test
  extends: .unittest-platoanalyze
  tags:
    - ${CONFIGURATION}
  needs: ["build-platoanalyze"]

test-platoanalyze:
  stage: test
  extends: .test-platoanalyze
  tags:
    - ${CONFIGURATION}
  needs: ["build-platoanalyze"]

test-platoanalyze-timing:
  stage: test
  extends: .test-platoanalyze-timing
  tags:
    - ${CONFIGURATION}
  needs: ["build-platoanalyze"]

teardown:
  stage: teardown
  extends: .clean-build-caches
  tags:
    - ${CONFIGURATION}
  needs:
    - job: "unittest-platoengine"
      optional: true
    - job: "unittest-platoanalyze"
      optional: true
    - job: "test-platoengine"
      optional: true
    - job: "test-platoanalyze"
      optional: true
    - job: "test-platoanalyze-timing"
      optional: true

