stages: [setup, build, test, coverage, teardown]

include:
  local: ci/*-templates.yml

merge-develop:
  stage: setup
  extends: .merge-with-develop
  tags:
    - ${CONFIGURATION}

setup-spack:
  stage: setup
  extends: .setup-local-spack-installation
  tags:
    - ${CONFIGURATION}
  needs: 
  - job: "merge-develop"
    optional: true

build-platoengine:
  stage: build
  extends: .build-and-cache-engine
  tags:
    - ${CONFIGURATION}
  needs: ["setup-spack"]

build-platoanalyze:
  stage: build
  extends: .build-and-cache-analyze
  tags:
    - ${CONFIGURATION}
  needs: ["build-platoengine"]

unittest-platoengine:
  stage: test
  parallel:
    matrix:
      - PLATO_ENGINE_UNIT_TESTER: [PlatoMainUnitTester, PlatoXMLGenerator_UnitTester, Plato_Operations_UnitTester, PlatoSu2ToExodus_UnitTester, PlatoTools_UnitTester, PlatoModels_UnitTester, PythonAppUnitTester]
  extends: .unittest-platoengine
  tags:
    - ${CONFIGURATION}
  needs: ["build-platoengine"]

test-platoengine:
  stage: test
  extends: .test-platoengine
  tags:
    - ${CONFIGURATION}
  needs: ["build-platoengine"]

unittest-platoanalyze:
  stage: test
  extends: .unittest-platoanalyze
  tags:
    - ${CONFIGURATION}
  needs: ["build-platoanalyze"]

test-platoanalyze:
  stage: test
  extends: .test-platoanalyze
  tags:
    - ${CONFIGURATION}
  needs: ["build-platoanalyze"]

merge-coverage-platoengine:
  stage: coverage
  extends: .coverage-platoengine
  parallel:
    matrix:
      - PLATO_ENGINE_FOLDER_PATTERN: [platoengine, analyze, data_layer, Filters, input_generator, interface, iso, models, operations, optimize, services, PlatoSubproblemLibrary, proxy, Su2Exodus, tools ]
  variables:
    PLATO_ENGINE_UNIT_TESTER: "PlatoMainUnitTester PlatoXMLGenerator_UnitTester Plato_Operations_UnitTester PlatoSu2ToExodus_UnitTester PlatoTools_UnitTester PlatoModels_UnitTester PythonAppUnitTester"
  tags:
    - ${CONFIGURATION}
  needs: ["unittest-platoengine"]
  when: always

coverage-report:
  stage: coverage
  extends: .coverage-report
  tags:
    - ${CONFIGURATION}
  needs: ["merge-coverage-platoengine"]

teardown:
  stage: teardown
  extends: .clean-build-caches
  tags:
    - ${CONFIGURATION}
  needs: 
    - job: "test-platoengine"
      optional: true
    - job: "unittest-platoengine"
      optional: true
    - job: "test-platoanalyze"
      optional: true
    - job: "unittest-platoanalyze"
      optional: true
