stages: [setup, build, test, teardown]

include:
  local: ci/*-templates.yml

merge-develop:
  stage: setup
  extends: .merge-with-develop
  tags:
    - ${SYSTEM}
    - ${EXECUTOR}

setup-spack:
  stage: setup
  extends: .setup-local-spack-installation
  tags:
    - ${SYSTEM}
    - ${EXECUTOR}
  needs:
  - job: "merge-develop"
    optional: true

build-dependencies:
  stage: build
  extends: .build-and-cache-dependencies
  tags:
    - ${SYSTEM}
    - ${EXECUTOR}
  needs: ["setup-spack"]

build-platoengine:
  stage: build
  extends: .build-and-cache-engine
  tags:
    - ${SYSTEM}
    - ${EXECUTOR}
  needs: ["build-dependencies"]

build-app:
  stage: build
  extends: .build-and-cache-app
  tags:
    - ${SYSTEM}
    - ${EXECUTOR}
  variables:
    BUILD_TYPE: ${APPLICATION}
  needs: ["build-platoengine"]

unittest-platoengine:
  stage: test
  extends: .unittest-platoengine
  tags:
    - ${SYSTEM}
    - ${EXECUTOR}
  needs: ["build-platoengine"]

unittest-coverage-platoengine:
  stage: test
  extends: .unittest-coverage-platoengine
  tags:
    - ${SYSTEM}
    - ${EXECUTOR}
  needs: ["build-platoengine"]

test-platoengine:
  stage: test
  extends: .test-platoengine
  tags:
    - ${SYSTEM}
    - ${EXECUTOR}
  needs: ["build-platoengine"]

unittest-platoanalyze:
  stage: test
  extends: .unittest-platoanalyze
  tags:
    - ${SYSTEM}
    - ${EXECUTOR}
  needs: ["build-platoanalyze"]

test-platoanalyze:
  stage: test
  extends: .test-platoanalyze
  tags:
    - ${SYSTEM}
    - ${EXECUTOR}
  needs: ["build-platoanalyze"]

test-platoanalyze-timing:
  stage: test
  extends: .test-platoanalyze-timing
  tags:
    - ${SYSTEM}
    - ${EXECUTOR}
  needs: ["build-platoanalyze"]

teardown:
  stage: teardown
  extends: .clean-build-caches
  tags:
    - ${SYSTEM}
    - ${EXECUTOR}
  needs:
    - job: "unittest-platoengine"
      optional: true
    - job: "unittest-platoanalyze"
      optional: true
    - job: "test-platoengine"
      optional: true
    - job: "test-platoanalyze"
      optional: true
    - job: "test-platoanalyze-timing"
      optional: true
